<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE persoane [
<!ELEMENT persoane (persoana+)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT persoana (nume , prenume,varsta,adresa)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada,numar,localitate,judet,tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
]>

<persoane>
    <persoana id="1">
        <nume>Chiriac</nume>
        <prenume>Ion</prenume>
        <varsta>21</varsta>
        <adresa>
        	<strada>nume_strada</strada>
        	<numar>22</numar>
        	<localitate>Iasi</localitate>
        	<judet>Iasi</judet>
        	<tara>Romania</tara>

        </adresa>
    </persoana>

    <persoana id="2">
        <nume>Tudor</nume>
        <prenume>Alexandru</prenume>
        <varsta>20</varsta>
        <adresa>
        	<strada>nume_strada1</strada>
        	<numar>23</numar>
        	<localitate>Bucuresti</localitate>
        	<judet>Bucuresti</judet>
        	<tara>Romania</tara>

        </adresa>
    </persoana>
</persoane>